### ISSUE TITLE
Preview Color of Role in s!role

### ISSUE THREAD

**Issue by Avakining** [greys-bots/sheep#16]
I think it would be nice if the role color was previewed in the embed from s!role so that people can see the color, instead of needing to understand the hex code.

**Comment by selenated** [comment]
Oddly enough, I thought we'd already done this! Can definitely change that 😅

**Comment by selenated** [comment]
Added in commit 30e609fbab6ed16f6a62e914aa96dfdb029baa82! Also it turns out we did add previewing before now, just not for that version of the command. Using `/admin roles view` will preview each individual role as if you were looking at it with `s!c`, letting you page through them to see them fully. For now with the text command we just went ahead and added a bit that `@mentions` the role to make it visible, since text commands will be retired soon

Thanks for the request! I'll go ahead and close this up now ^^
